// WHAT JAVASCRIPT CAN DO WITH WEBPAGES ?

// 1. YOU CAN ACCESSING THE WEBPAGE ELEMENTS USING JAVASCRIPT PROGRAMS.
// 2. YOU CAN CHANGE THE CONTENT OF THE WEBPAGE DYNAMICALLY WITH JAVASCRIPT.
// 3. WITH JAVASCRIPT, YOU CAN MANIPULATE WEBPAGE ELEMENTS ACCORDING TO YOUR NEED.
// 4. YOU CAN ALSO ADD DYNAMIC CONTENT TO THE WEBPAGE.

// WHAT IS DOM ?
// 1. DOM STANDS FOR DOCUMENT OBJECT MODEL.
// 2. DOM IS STRUCTURED REPRESENTATION OF HTML ELEMENTS AS AN OBJECT.
// 3. WHEN A WEBPAGE IS LOADED IN THE BROWSER, THE BROWSER CREATES AN OBJECT FOR EACH ELEMENT OF THE HTML PAGE IN DOM.
// 4. ONCE THE DOM IS CREATED FOR THE WEBPAGE, WE CAN ACCESS THE DOM ELEMNTS USING SCRIPTS SUCH AS JAVASCRIPT AND CAN MANIPULATE IT.

// WHERE IS THIS DOCUMENT OBJECT PRESENT ?
// JAVASCRIPT PROGRAMS ARE EXECUTED IN A RUNTIME ENVIRONMENT. WHEN WE RUN JAVSCRIPT PROGRAM IN BROWSER, THE RUNTIME ENVIRONMENT IS THE BROWSER.
// EVERY RUNTIME ENVIRONMENT HAS A GLOBAL OBJECT. IN CASE OF BROWSERS, THE GLOBAL OBJECT IS THE WINDOW OBJECT.
// IT IS THIS WINDOW OBJECT, WHICH CONTAINS THE DOCUMENT OBJECT.

// HTML DOCUMENT NOT NECESSARILY REPRESENTS THE DOM.
// ALTHOUGH THE DOM IS CREATED FROM THE SOURCE HTML DOCUMENT, IT IS NOT ALWAYS TRUE. THERE ARE TWO INSTANCES WHERE THE DOM CAN BE DIFFERENT FORM THE SOURCE HTML.

// 1. WHEN HTML IS NOT VALID
// THE DOM IS AN INTERFACE FOR VALID HTML DOCUMENTS. DURING THE PROCESS OF CREATING THE DOM, THE BROWSER MAY CORRECT SOME INVALIDITIES IN THE HTML CODE.

/*
    <!DOCTYPE html>
    <html>
        Hello, World
    </html>
*/

// 2. WHEN DOM IS MODIFIED BY JAVASCRIPT
// BESIDES BEING THE INTERFACE OF VIEWING THE CONTENT OF HTML, DOM CAN ALSO BE MODIFIED USING EXTERNAL SCRIPTS LIKE JAVASCRIPT PROGRAMS.

/*
IN THE BELOW EXAMPLE, DOM HAS BEEN CREATED BUT IT WILL NOT ADDED TO HTML DOCUMENT.
let newParagraph = document.createElement('p');
let pContent = document.createTextNode('I am new!');
newParagraph.appendChild(pContent);
document.body.appendChild(newParagraph)
*/

//! SUMMARY

/*
    THE HTML DOM IS A STANDARD OBJECT MODEL AND PROGRANMMING INTERFACE FOR HTML. IT DEFINES
    1. THE HTML ELEMENTS AS OBJECTS.
    2. THE PROPERTIES OF ALL HTML ELEMENTS.
    3  THE METHODS TO ACCESS ALL HTML ELEMENTS.
    4. THE EVENTS FOR ALL HTML ELEMENTS.

    IN OTHER WORDS, THE HTML DOM IS A STANDARD FOR HOW TO ACCESS, CHANGE, ADD OR DELETE HTML ELEMENTS.
*/