// MODAL WINDOWS
// WHEN THE MODAL WINDOW APPEARS ON THE WEB PAGE THEN WEBAPGE BECOMES IRRESPONSIVE.(THEY PAUSE JAVASCRIPT CODE TO EXECUTE)

// IN JAVASCRIPT, THERE ARE THREE MODAL WINDOWS:
// 1. Alert => USED TO SHOW A MESSAGE TO THE USER.
// alert("Welcome to Javscript course");

// 2. Prompt => USED TO TAKE INPUT FROM THE USER.
// 1. RETURNS THE VALUE ENTERED IN THE INPUT FIELD WHEN OK BUTTON IS CLICKED.
// 2. EMPTY STRING IS RETURNED IF NOTHING IS ENTERED IN THE INPUT FIELD AND OK BUTTON IS CLICKED.
// 3. NULL IS RETURNED WHEN USER CLICK ON THE CANCEL BUTTON.
// 4. PROMPT MODAL WINDOW RETURNS THE STRING VALUE.

let age = prompt("Please enter your age", 20);
console.log(age);

// 3. Confirm => USED TO GET CONFIRMATION FROM THE USER.
// 1. RETURNS TRUE WHEN USER CLICKS ON THE OK BUTTON
// 2. RETURNS FALSE WHEN USER CLICKS ON THE CANCEL BUTTON
let del = confirm('Do you really want to delete this item?');
console.log(del);

if(del) {
    // WRITE THE LOGIC TO DELETE THE ITEM
}

