// AJAX

// 1. AJAX STANDS FOR ASYNCHRONOUS JAVASCRIPT AND XML.
// 2. AJAX IS NOT PROGRAMMING LANGUAGE, BUT IT IS A SET OF EXISTING WEB TECHNOLOGIES.
// 3. AJAX HELPS IN FETCHING DATA ASYNCHRONOUSLY FROM A REMOTE WEB SERVER.
// 4. WHEN THE DATA IS LOADED BY AJAX, IT IS LOADED ASYNCHRONOUSLY WITHOUT PAGE RELOAD / REFRESH.
// 5. MODERN WEBSITES USES JSON FORMAT INSTEAD OF XML, FOR DATA TRANSFER.

// ADVANTAGE OF USING AJAX

// 1. AJAX LOADS DATA DYNAMICALLY INTO A WEBPAGE WITHOUT RELOADING THE COMPLETE WEBPAGE.
// 2. IT PROVIDES BETTER USER EXPERIENCE BY NOT MAKING THE COMPLETE WEBPAGE UNRESPONSIVE WHILE LOADING THE DATA INTO THE WEBPAGE.
// 3. IT SAVES NETWORK BANDWIDTH BECAUSE ONLY A PART OF THE WEBPAGE IS BEING LOADED AND NOT COMPLETE WEB PAGE.
// 4. IT MAKES THE WEBPAGE MORE INTERACTIVE. SINCE THE REQUEST SENT TO THE NETWORK IS DONE IN AN ASYNCHRONOUS WAY. IT WILL NOT MAKE THE WEBPAGE UNRESPONSIVE.
