// ASYNCHRONOUS JAVASCRIPT AND AJAX

// SYNCHRONOUS PROGRAM

// 1. JAVASCRIPT IS A SINGLE THREADED PROGRAMMING LANGUAGE. THAT MEANS THERE IS ONLY ONE THREAD WHICH EXECUTES ALL THE JAVASCRIPT CODE. BECAUSE OF THIS, JAVASCRIPT ENGINE CAN PROCESS ONLY ONE STATEMNET AT A TIME.
// 2. IN SYNCHRONOUS PROGRAMMING, CODE IS EXECUTED LINE BY LINE IN THE ORDER OF ITS EXECUTION.
// 3. IF ANY PART OF THE CODE IS TAKING LONG TIME IN ITS EXECUTION (DUE TO LONG RUNNING OPERATION SUCH AS NETWORK ACCESS), THEN THE NEXT STATEMENT WILL HAVE TO WAIT FOR ITS EXECUTION TO COMPLETE.
// 4. MOST OF THE CODE WHICH WE WRITE IN JAVASCRIPT, IS SYNCHRONOUS CODE.

// EX-1:
// let helloWorld = function() {
//     console.log('Hello, World');
// }

// let greetings = function() {
//     console.log('Good Morning!');
//     helloWorld();
//     console.log('Have a good day');
// }

// greetings();

// EX-2:
// let str = "Good Morning";
// console.log(str);
// alert('This is an alert window');
// console.log('have a good day!');

// ASYNCHRONOUS PROGRAM

// 1. IN ASYNCHRONOUS PROGRAM, WE CAN EXECUTE PIECE OF CODE ASYNCHRONOUSLY IN THE BACKGROUND. AN ASYNCHRONOUS CODE DOES NOT BLOCK THE EXECUTION OF NEXT LINE OF CODES.
// 2. THERE ARE MANY FUNCTIONS AND APIs PROVIDED BY THE BROWSERS WEBAPI, WHICH GETS EXECUTED ASYNCHRONOUSLY IN THE BACKGROUND WITHOUT BLOCKING THE CODE EXECUTION. ONE SUCH FUNCTION IS setTimeout() FUNCTION.
// 3. ASYNCHRONOUS CODE IS NON-BLOCKING.
// 4. IT DOES NOT STOP THE EXECUTION OF MAIN CODE.

// EX-1:
let str = 'Good Morning';
console.log(str);
setTimeout(function() {
    alert('This is an alert window');
}, 5000);
console.log('have a good day!');