// NULLISH COALESCING OPERATOR

// THE NULLISH COALESCING OPERATOR IS USED TO HANDLE NULL OR UNDEFINED VALUES IN JAVASCRIPT.
// IT IS A LOGICAL OPERATOR. (BINARY OPERATOR)
// IT IS REPRESENTED BY ??. FOR EXAMPLE VALUE = A ?? B
// NULLISH COALESCING OPERATOR RETURNS THE VALUE OF FIRST OPERAND IF ITS VALUE IS NOT NULL OR UNDEFINED. OTHERWISE IT RETURNS THE VALUE OF SECOND OPERAND.
// IT IS SHORT HAND PROPERTY OF TERNERY OPERATOR

let a = 100;
let b = "Height is not defined";
let height;

// height = (a == null || a == undefined) ? b : a; // USING TERNERY OPERATOR
// height = a ?? b;    // USING NULLISH COALESCING
// console.log(height);

//! DIFFERENCE BETWEEN OR OPERATOR AND NULLISH COALESCING OPERATOR

//? OR OPERATOR RETURNS FIRST TRUTHY VALUES
// TRUTHY VALUES => EVERYTHING ACCEPT (0, "", NULL, UNDEFINED, FALSE)

// height = a || b;  
// console.log(height);

//? NULLISH COALESCING OPERATOR RETURNS THE VALUE OF FIRST OPERAND IF ITS VALUE IS NOT NULL OR UNDEFINED. OTHERWISE IT RETURNS THE VALUE OF SECOND OPERAND.

height = a ?? b;  
console.log(height);

